// Collect the Astro source's CSS into one stylesheet for the Next build.
//
// Every style in this theme lives in src/styles/global.css (with any @imports
// inlined); the Sora font faces come from @fontsource/sora in both builds.
// Astro scopes component <style> blocks and one flat file cannot, so the
// script refuses to run if a component grows a <style> block whose root
// classes another component also styles, or uses :global / is:global.
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from 'node:fs';
import { join, dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const A = join(ROOT, 'src');
const OUT = join(ROOT, 'next', 'src', 'styles', 'site.css');
const walk = (d) => readdirSync(d).flatMap((f) => (statSync(join(d, f)).isDirectory() ? walk(join(d, f)) : [join(d, f)]));
const inline = (file) => readFileSync(file, 'utf8').replace(/@import\s+['"](\..+?)['"];?/g, (_, p) => inline(join(dirname(file), p)));

const files = walk(A).filter((f) => f.endsWith('.astro')).map((f) => relative(A, f).replace(/\\/g, '/')).sort();
const owners = new Map();
const problems = [];
const parts = ['/* GENERATED by tools/collect-css.mjs from the Astro source. Edit src/styles/global.css, then regenerate. */', inline(join(A, 'styles', 'global.css')).trim()];

for (const rel of files) {
  const src = readFileSync(join(A, rel), 'utf8');
  for (const [, attrs = '', css] of src.matchAll(/<style(\s[^>]*)?>([\s\S]*?)<\/style>/g)) {
    if (/is:global|define:vars|is:inline/.test(attrs)) problems.push(`${rel}: <style${attrs}> is not allowed`);
    if (/:global\(/.test(css)) problems.push(`${rel}: :global() is not allowed`);
    const bare = css.replace(/\/\*[\s\S]*?\*\//g, '');
    for (const m of bare.matchAll(/(?<=^|[{};])([^{};]+)\{/g)) {
      const sel = m[1].trim();
      if (!sel || sel.startsWith('@')) continue;
      for (const one of sel.split(',')) {
        const s = one.trim();
        if (!s || /^(from|to|\d+%)$/.test(s)) continue;
        const cls = s.match(/\.([A-Za-z_][\w-]*)/);
        if (!cls) { problems.push(`${rel}: selector without a component class: "${s}"`); continue; }
        const prev = owners.get(cls[1]);
        if (prev && prev !== rel) problems.push(`.${cls[1]} is styled in both ${prev} and ${rel}`);
        else owners.set(cls[1], rel);
      }
    }
    parts.push(`/* ---- ${rel} ---- */\n${css.trim()}`);
  }
}
// global.css must not restyle a class a component <style> owns either.
for (const [cls, rel] of owners) if (new RegExp(`\\.${cls}\\b`).test(parts[1])) problems.push(`.${cls} is styled in both global.css and ${rel}`);

if (problems.length) {
  console.error('collect-css refused:\n  ' + [...new Set(problems)].join('\n  '));
  process.exit(1);
}
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, parts.join('\n\n') + '\n');
console.log(`${files.length} .astro files scanned, ${parts.length - 2} component <style> blocks -> ${relative(ROOT, OUT)}`);
